package com.application.spring;

import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;

@Configuration
public class SwaggerConfig {
    @Bean
    OpenAPI customOpenAPI() {
        return new OpenAPI()
                .openapi("3.0.1") // Specify the OpenAPI version
                .info(new Info()
                        .title("Greedys API")
                        .version("1.0")
                        .description("API for managing restaurant reservations"))
                .components(new Components()
                        .addSchemas("GenericResponse", new Schema<>()
                                .type("object")
                                .addProperty("message",
                                        new Schema<String>().type("string"))
                                .addProperty("error",
                                        new Schema<String>().type("string"))) // Aggiunto
                        // attributo
                        // error
                        .addResponses("400", new ApiResponse().description("Bad Request"))
                        .addResponses("401", new ApiResponse().description("Unauthorized"))
                        .addResponses("403", new ApiResponse().description("Forbidden"))
                        .addResponses("404", new ApiResponse().description("Not Found"))
                        .addResponses("500", new ApiResponse()
                                .description("Internal Server Error")));
    }

    @Bean
    public GroupedOpenApi adminApi() {
        return GroupedOpenApi.builder()
                .group("admin-api")
                .pathsToMatch("/admin/**")
                .packagesToScan("com.application.controller.admin",
                        "com.application.controller.admin.test")
                .addOpenApiCustomizer(openApi -> openApi
                        .components(sharedComponents()
                                .addSecuritySchemes("adminBearerAuth",
                                        new SecurityScheme()
                                                .type(SecurityScheme.Type.HTTP)
                                                .scheme("bearer")
                                                .bearerFormat("JWT"))
                                .addSchemas("RestaurantCategoryDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("NewTableDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idRestaurant", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("roomId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("capacity", new Schema<Integer>().type("integer"))
                                        .addProperty("positionX", new Schema<Integer>().type("integer"))
                                        .addProperty("positionY", new Schema<Integer>().type("integer")))
                                .addSchemas("NewRoomDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idRestaurant", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("RestaurantDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string")))
                                .addSchemas("ServiceDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("RoomDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("ReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string")))
                                .addSchemas("PageReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("content", new Schema<>().type("array").items(new Schema<>().$ref("#/components/schemas/ReservationDTO")))
                                        .addProperty("totalElements", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("totalPages", new Schema<Integer>().type("integer")))
                                .addSchemas("TableDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("Pageable", new Schema<>()
                                        .type("object")
                                        .addProperty("page", new Schema<Integer>().type("integer"))
                                        .addProperty("size", new Schema<Integer>().type("integer")))
                                .addSchemas("AdminNewReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idSlot", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string")))
                                .addSchemas("NewAdminDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string")))
                                .addSchemas("ServiceTypeDto", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("SlotDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("startTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("endTime", new Schema<String>().type("string").format("time")))
                                .addSchemas("AdminNewServiceDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string")))
                                .addSchemas("PageCustomerDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("content", new Schema<>().type("array").items(new Schema<>().$ref("#/components/schemas/CustomerDTO")))
                                        .addProperty("totalElements", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("totalPages", new Schema<Integer>().type("integer")))
                                .addSchemas("AllergyDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string")))
                                .addSchemas("NotificationRequest", new Schema<>()
                                        .type("object")
                                        .addProperty("title", new Schema<String>().type("string"))
                                        .addProperty("message", new Schema<String>().type("string")))
                                .addSchemas("EmailRequestDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("to", new Schema<String>().type("string"))
                                        .addProperty("subject", new Schema<String>().type("string"))
                                        .addProperty("body", new Schema<String>().type("string")))
                                .addSchemas("NewAllergyDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string"))))
                        .addSecurityItem(new SecurityRequirement().addList("adminBearerAuth")))
                .build();
    }

    @Bean
    public GroupedOpenApi customerApi() {
        return GroupedOpenApi.builder()
                .group("customer-api")
                .pathsToMatch("/customer/**")
                .packagesToScan("com.application.controller.customer")
                .addOpenApiCustomizer(openApi -> openApi
                        .components(sharedComponents()
                                .addSecuritySchemes("customerBearerAuth",
                                        new SecurityScheme()
                                                .type(SecurityScheme.Type.HTTP)
                                                .scheme("bearer")
                                                .bearerFormat("JWT"))
                                .addSchemas("PageNotification", new Schema<>()
                                        .type("object")
                                        .addProperty("content", new Schema<>().type("array").items(new Schema<>().$ref("#/components/schemas/NotificationDTO")))
                                        .addProperty("totalElements", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("totalPages", new Schema<Integer>().type("integer")))
                                .addSchemas("UserFcmTokenDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("userId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("fcmToken", new Schema<String>().type("string"))
                                        .addProperty("createdAt", new Schema<String>().type("string").format("date-time"))
                                        .addProperty("deviceId", new Schema<String>().type("string")))
                                .addSchemas("CustomerDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string"))
                                        .addProperty("status", new Schema<String>().type("string")))
                                .addSchemas("UpdatePasswordDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("currentPassword", new Schema<String>().type("string"))
                                        .addProperty("newPassword", new Schema<String>().type("string"))
                                        .addProperty("confirmPassword", new Schema<String>().type("string")))
                                .addSchemas("NewCustomerDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string"))
                                        .addProperty("password", new Schema<String>().type("string"))
                                        .addProperty("matchingPassword", new Schema<String>().type("string")))
                                .addSchemas("ReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string"))
                                        .addProperty("reservationDay", new Schema<String>().type("string").format("date")))
                                .addSchemas("CustomerNewReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idSlot", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string"))
                                        .addProperty("reservationDay", new Schema<String>().type("string").format("date"))
                                        .addProperty("restaurant_id", new Schema<Long>().type("integer").format("int64"))))
                        .addSecurityItem(new SecurityRequirement()
                                .addList("customerBearerAuth")))
                .build();
    }

    @Bean
    public GroupedOpenApi restaurantApi() {
        return GroupedOpenApi.builder()
                .group("restaurant-api")
                .pathsToMatch("/restaurant/**")
                .packagesToScan("com.application.controller.restaurantUser")
                .addOpenApiCustomizer(openApi -> openApi
                        .components(sharedComponents()
                                .addSecuritySchemes("restaurantBearerAuth",
                                        new SecurityScheme()
                                                .type(SecurityScheme.Type.HTTP)
                                                .scheme("bearer")
                                                .bearerFormat("JWT"))
                                .addSchemas("ReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string")))
                                .addSchemas("PageReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("content", new Schema<>().type("array").items(new Schema<>().$ref("#/components/schemas/ReservationDTO")))
                                        .addProperty("totalElements", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("totalPages", new Schema<Integer>().type("integer")))
                                .addSchemas("TableDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("RoomDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("ServiceDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("NewRoomDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idRestaurant", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("NewTableDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idRestaurant", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("roomId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("capacity", new Schema<Integer>().type("integer"))
                                        .addProperty("positionX", new Schema<Integer>().type("integer"))
                                        .addProperty("positionY", new Schema<Integer>().type("integer")))
                                .addSchemas("PageRestaurantNotification", new Schema<>()
                                        .type("object")
                                        .addProperty("content", new Schema<>().type("array").items(new Schema<>().$ref("#/components/schemas/RestaurantNotification")))
                                        .addProperty("totalElements", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("totalPages", new Schema<Integer>().type("integer")))
                                .addSchemas("RestaurantNotification", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("type", new Schema<String>().type("string"))
                                        .addProperty("opened", new Schema<Boolean>().type("boolean")))
                                .addSchemas("RestaurantUserDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("user_id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("restaurant_id", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("RestaurantNewReservationDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("idSlot", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("pax", new Schema<Integer>().type("integer"))
                                        .addProperty("kids", new Schema<Integer>().type("integer"))
                                        .addProperty("notes", new Schema<String>().type("string"))
                                        .addProperty("reservationDay", new Schema<String>().type("string").format("date"))
                                        .addProperty("restaurant_id", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("MenuItemDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string")))
                                .addSchemas("RestaurantMenuDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string")))
                                .addSchemas("NewMenuItemDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string"))
                                        .addProperty("restaurantId", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("NewPricedMenuItemDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("itemId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("menuId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("price", new Schema<Double>().type("number").format("double")))
                                .addSchemas("PricedMenuItemDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("itemId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("menuId", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("price", new Schema<Double>().type("number").format("double")))
                                .addSchemas("NewRestaurantMenuDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string"))
                                        .addProperty("price", new Schema<Double>().type("number").format("double"))
                                        .addProperty("restaurantId", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("ServiceTypeDto", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("SlotDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("startTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("endTime", new Schema<String>().type("string").format("time")))
                                .addSchemas("RestaurantNewServiceDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("description", new Schema<String>().type("string")))
                                .addSchemas("RestaurantNewSlotDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("startTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("endTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("serviceId", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("NewSlotDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("startTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("endTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("serviceId", new Schema<Long>().type("integer").format("int64"))))
                        .addSecurityItem(new SecurityRequirement()
                                .addList("restaurantBearerAuth")))
                .build();
    }

    @Bean
    public GroupedOpenApi publicApi() {
        return GroupedOpenApi.builder()
                .group("public-api")
                .packagesToScan("com.application.controller.pub")
                .pathsToMatch("/public/**", "/register/**", "/auth/**")
                .pathsToExclude("/restaurant/**", "/customer/**", "/admin/**")
                .addOpenApiCustomizer(openApi -> openApi
                        .components(sharedComponents()
                                .addSchemas("AuthRequestDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("username", new Schema<String>().type("string"))
                                        .addProperty("password", new Schema<String>().type("string")))
                                .addSchemas("AuthResponseDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("jwt", new Schema<String>().type("string"))
                                        .addProperty("user", new Schema<>().$ref("#/components/schemas/CustomerDTO")))
                                .addSchemas("AdminAuthResponseDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("jwt", new Schema<String>().type("string"))
                                        .addProperty("user", new Schema<>().$ref("#/components/schemas/AdminDTO")))
                                .addSchemas("AdminDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string")))
                                .addSchemas("AuthRequestGoogleDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("token", new Schema<String>().type("string")))
                                .addSchemas("CustomerDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string"))
                                        .addProperty("status", new Schema<String>().type("string")))
                                .addSchemas("NewCustomerDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("firstName", new Schema<String>().type("string"))
                                        .addProperty("lastName", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string"))
                                        .addProperty("password", new Schema<String>().type("string"))
                                        .addProperty("matchingPassword", new Schema<String>().type("string")))
                                .addSchemas("RestaurantDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string")))
                                .addSchemas("RoomDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("ServiceDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("SlotDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("startTime", new Schema<String>().type("string").format("time"))
                                        .addProperty("endTime", new Schema<String>().type("string").format("time")))
                                .addSchemas("TableDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("name", new Schema<String>().type("string")))
                                .addSchemas("RestaurantUserAuthResponseDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("jwt", new Schema<String>().type("string"))
                                        .addProperty("user", new Schema<>().$ref("#/components/schemas/RestaurantUserDTO")))
                                .addSchemas("RestaurantUserDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("user_id", new Schema<Long>().type("integer").format("int64"))
                                        .addProperty("restaurant_id", new Schema<Long>().type("integer").format("int64")))
                                .addSchemas("NewRestaurantDTO", new Schema<>()
                                        .type("object")
                                        .addProperty("name", new Schema<String>().type("string"))
                                        .addProperty("email", new Schema<String>().type("string"))
                                        .addProperty("password", new Schema<String>().type("string")))))
                .build();
    }

    private Components sharedComponents() {
        return new Components()
                .addSchemas("GenericResponse", new Schema<>()
                        .type("object")
                        .addProperty("message", new Schema<String>().type("string"))
                        .addProperty("error", new Schema<String>().type("string")));
    }
}
